[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "5xjzBZvz6cTaCQDRy62jerJMk3QCMHoie3EfXTtVSqtr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./turbin3-wallet.json"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
